export const CartActionTypes = {
    TOGGLE_CART_ITEMS:'TOGGLE_CART_ITEMS',
    ADD_ITEMS:'ADD_ITEMS',
    REMOVE_CART_ITEMS:'REMOVE_CART_ITEMS',
    REMOVE_QUANTITY:'REMOVE_QUANTITY',
    SET_GOTO_PAGE:'SET_GOTO_PAGE',
    CLEAR_CART:'CLEAR_CART'
}