export const CATEGORIES = [
    {
        name:'vegetables',
        url:'shop/vegetables',
        imgUrl:''
    },
    {
        name:'fruits',
        url:'shop/fruits',
        imgUrl:''
    },
    {
        name:'meat',
        url:'shop/meat',
        imgUrl:''
    },
    {
        name:'spices',
        url:'shop/spices',
        imgUrl:''
    },
    {
        name:'seafood',
        url:'shop/seafood',
        imgUrl:''
    },
    {
        name:'frozen',
        url:'shop/frozen',
        imgUrl:''
    },
    {
        name:'grains',
        url:'shop/grains',
        imgUrl:''
    },
    {
        name:'snacks',
        url:'shop/snacks',
        imgUrl:''
    },
    {
        name:'drinks',
        url:'shop/drinks',
        imgUrl:''
    },
]
